import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbars from '../Components/Navbar/navbar'
import { Suspense } from "react";
import Loading from '../app/loading'

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbars />
        <Suspense fallback={<Loading />}>
        {children}
        </Suspense>
        </body>
    </html>
  );
}
